---
discord_log_path: "log/discord.log"
discord_bot_token: "BOT TOKEN"

db_log_path: 'log/db.log'
db_path: 'db/adventure_bot.db'

adventure_log_path: 'log/adventures.log'
adventure_path: 'adventures/'